let SHOP_MENU_WEEK_OFFSET = 0;
let SHOP_MENU_CACHE = null;

let MENU_DASHBOARD_MONTH = "";
let MENU_DASHBOARD_SELECTED_DATE = "";
let MENU_DASHBOARD_VIEW = "menu";
let MENU_DASHBOARD_SERVINGS = 100;
let MENU_DASHBOARD_CACHE = null;

function menuText(v){ return String(v ?? "").trim(); }
function menuEscape(v){
  return menuText(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
}
function menuNum(v, d=0){ const n = Number(v); return Number.isFinite(n) ? n : d; }
function menuQty(v){ const n = Number(v); return Number.isFinite(n) && n > 0 ? n : 1; }
function menuIntQty(v){ const n = Math.floor(Number(v)); return Number.isFinite(n) && n > 0 ? n : 1; }
function menuFormatAmount(v, digits=0){
  const n = Number(v);
  if (!Number.isFinite(n)) return digits > 0 ? (0).toFixed(digits) : '0';
  if (digits > 0) return n.toFixed(digits).replace(/\.0+$/,'').replace(/(\.\d*?)0+$/,'$1');
  return String(Math.round(n));
}
function menuFormatWeight(v, unit){
  const n = Number(v);
  const rawUnit = menuText(unit) || 'g';
  if (!Number.isFinite(n)) return { value: '0', unit: rawUnit.toUpperCase(), sub: '' };
  if (/^(g|公克|克)$/i.test(rawUnit) && Math.abs(n) >= 1000) return { value: menuFormatAmount(n/1000,2), unit:'KG', sub:`(${menuFormatAmount(n,0)}g)` };
  return { value: menuFormatAmount(n, /^(kg|公斤)$/i.test(rawUnit) ? 2 : 0), unit: rawUnit.toUpperCase(), sub:'' };
}
function menuTodayIso(){ const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`; }
function menuTodayKey(){ return menuTodayIso().replace(/-/g,''); }
function menuMonthKeyFromDate(dateStr){ const text = menuText(dateStr); return /^\d{4}-\d{2}-\d{2}$/.test(text) ? text.slice(0,7) : menuTodayIso().slice(0,7); }
function menuShiftMonth(monthKey, delta){ const base = /^\d{4}-\d{2}$/.test(menuText(monthKey)) ? `${monthKey}-01` : `${menuTodayIso().slice(0,7)}-01`; const dt = new Date(`${base}T00:00:00`); dt.setMonth(dt.getMonth()+Number(delta||0)); return `${dt.getFullYear()}-${String(dt.getMonth()+1).padStart(2,'0')}`; }
function getMenuEl(id){ return document.getElementById(id); }
function isStandaloneWeeklyMenuPage(){ return !!getMenuEl('menu-dashboard-page-root'); }
function isShopIndexMenuRail(){ return !!getMenuEl('shop-menu-rail-list'); }

function updateShopMenuWeekLabel(payload){ const el = getMenuEl('shop-menu-week-label'); if (el) el.textContent = payload ? `${menuText(payload.week_start_label)} ～ ${menuText(payload.week_end_label)}` : ''; }
function setShopMenuRailStatus(text, isError){ const status=getMenuEl('shop-menu-rail-status'); const list=getMenuEl('shop-menu-rail-list'); if(!status||!list)return; status.style.display=''; status.innerHTML=text; status.style.color=isError?'#b91c1c':'#6b7280'; list.style.display='none'; list.innerHTML=''; }
function renderShopMenuRail(){
  if(!isShopIndexMenuRail()) return;
  const payload=SHOP_MENU_CACHE, list=getMenuEl('shop-menu-rail-list'), status=getMenuEl('shop-menu-rail-status');
  updateShopMenuWeekLabel(payload);
  if(!list||!status)return;
  const days=Array.isArray(payload&&payload.days)?payload.days:[];
  if(!days.length){ setShopMenuRailStatus('這一週沒有可顯示的菜單日期。', true); return; }
  status.style.display='none'; list.style.display='';
  const todayKey=menuTodayKey();
  list.innerHTML=days.map(day=>`<button type="button" class="shop-menu-rail__day${String(day.date||'').replace(/[^0-9]/g,'')===todayKey?' is-today':''}" onclick="openWeeklyMenuModalForDate('${menuEscape(day.date)}')"><div class="shop-menu-rail__day-top">${menuEscape(day.display_date||day.date)}</div><div class="shop-menu-rail__day-sub">${menuEscape(day.weekday_label||'')}</div><div class="shop-menu-rail__day-meta">農曆 ${menuEscape(day.lunar||'—')}</div><div class="shop-menu-rail__day-tag${day.has_menu?'':' is-empty'}">${day.has_menu?'開啟菜單':'尚無菜單'}</div></button>`).join('');
}
function loadShopMenuRail(){ if(!isShopIndexMenuRail()) return; setShopMenuRailStatus('正在讀取本週日期…', false); callGAS({type:'weeklyMenu', offset:SHOP_MENU_WEEK_OFFSET}, res=>{ if(!res||res.status!=='ok'){SHOP_MENU_CACHE=null; updateShopMenuWeekLabel(null); setShopMenuRailStatus(`日期資料載入失敗：${menuEscape(res&&res.message?res.message:'未知錯誤')}`, true); return;} SHOP_MENU_CACHE=res; renderShopMenuRail(); }); }
function changeShopMenuWeek(step){ SHOP_MENU_WEEK_OFFSET += Number(step)||0; loadShopMenuRail(); }
function resetShopMenuWeek(){ SHOP_MENU_WEEK_OFFSET = 0; loadShopMenuRail(); }

function menuDashboardShellHtml(isModal){ return `<div class="menu-dashboard-shell${isModal?' is-modal':''}"><aside class="menu-dashboard-sidebar"><div class="menu-dashboard-brand"><div class="menu-dashboard-brand__logo">YQ</div><div><h1>共同採購平台</h1><p>每日菜單與採購試算</p></div></div><section class="menu-calendar-panel"><div class="menu-calendar-panel__head"><div><div class="menu-calendar-panel__eyebrow">Navigator</div><div id="menu-dashboard-month-label" class="menu-calendar-panel__month">載入中…</div></div><div class="menu-calendar-panel__nav"><button type="button" onclick="changeMenuDashboardMonth(-1)">‹</button><button type="button" onclick="resetMenuDashboardMonth()">●</button><button type="button" onclick="changeMenuDashboardMonth(1)">›</button></div></div><div class="menu-calendar-weekdays"><span>日</span><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span></div><div id="menu-dashboard-calendar" class="menu-calendar-grid"></div></section></aside><section class="menu-dashboard-main"><div class="menu-dashboard-topbar"><div class="menu-dashboard-tabs"><button id="menu-tab-menu" type="button" class="menu-dashboard-tab is-active" onclick="setMenuDashboardView('menu')">每日菜單</button><button id="menu-tab-procurement" type="button" class="menu-dashboard-tab" onclick="setMenuDashboardView('procurement')">採購試算</button></div><div class="menu-dashboard-actions"><a href="index.html" class="menu-dashboard-link">採購平台</a>${isModal?'<button type="button" class="menu-dashboard-close" onclick="closeWeeklyMenuModal()">✕</button>':''}</div></div><div class="menu-dashboard-hero"><div><h2 id="menu-dashboard-date-title">載入中…</h2><div id="menu-dashboard-date-sub" class="menu-dashboard-date-sub"></div></div></div><div id="menu-dashboard-status" class="menu-dashboard-status">正在讀取菜單資料…</div><div id="menu-dashboard-view"></div></section></div>`; }
function ensureWeeklyMenuModal(){ if(isStandaloneWeeklyMenuPage()||getMenuEl('weekly-menu-modal')) return; const wrap=document.createElement('div'); wrap.innerHTML=`<div id="weekly-menu-modal" class="weekly-menu-modal" aria-hidden="true"><div class="weekly-menu-modal__backdrop" onclick="closeWeeklyMenuModal()"></div><div class="weekly-menu-modal__dialog">${menuDashboardShellHtml(true)}</div></div>`; document.body.appendChild(wrap.firstElementChild); }
function initStandaloneDashboard(){ const root=getMenuEl('menu-dashboard-page-root'); if(root) root.innerHTML=menuDashboardShellHtml(false); }
function setMenuDashboardStatus(text,isError){ const box=getMenuEl('menu-dashboard-status'); if(!box)return; box.style.display=''; box.className=`menu-dashboard-status${isError?' is-error':''}`; box.innerHTML=text; }
function hideMenuDashboardStatus(){ const box=getMenuEl('menu-dashboard-status'); if(box) box.style.display='none'; }
function currentMenuDay(){ return MENU_DASHBOARD_CACHE&&MENU_DASHBOARD_CACHE.selected_day?MENU_DASHBOARD_CACHE.selected_day:null; }
function syncMenuDashboardTitle(){ const payload=MENU_DASHBOARD_CACHE, day=currentMenuDay(); const title=getMenuEl('menu-dashboard-date-title'), sub=getMenuEl('menu-dashboard-date-sub'), month=getMenuEl('menu-dashboard-month-label'); if(title) title.textContent=day&&day.date?day.date:'每日菜單中心'; if(sub) sub.textContent=day?`${menuText(day.weekday_label||'')}｜農曆 ${menuText(day.lunar||'—')}｜${day.has_menu?'已建立菜單':'尚無菜單'}`:'請從左側日曆選擇日期'; if(month) month.textContent=payload?menuText(payload.month_label||payload.month||''):''; }
function setMenuDashboardView(view){ MENU_DASHBOARD_VIEW=['menu','procurement'].includes(view)?view:'menu'; ['menu','procurement'].forEach(key=>{ const btn=getMenuEl(`menu-tab-${key}`); if(btn) btn.classList.toggle('is-active', MENU_DASHBOARD_VIEW===key); }); renderMenuDashboardView(); }
function changeMenuDashboardMonth(step){ MENU_DASHBOARD_MONTH=menuShiftMonth(MENU_DASHBOARD_MONTH||menuMonthKeyFromDate(MENU_DASHBOARD_SELECTED_DATE||menuTodayIso()), step); MENU_DASHBOARD_SELECTED_DATE=`${MENU_DASHBOARD_MONTH}-01`; loadMenuDashboard(); }
function resetMenuDashboardMonth(){ MENU_DASHBOARD_MONTH=menuTodayIso().slice(0,7); MENU_DASHBOARD_SELECTED_DATE=menuTodayIso(); loadMenuDashboard(); }
function selectMenuDashboardDate(date){ MENU_DASHBOARD_SELECTED_DATE=menuText(date); MENU_DASHBOARD_MONTH=menuMonthKeyFromDate(MENU_DASHBOARD_SELECTED_DATE); loadMenuDashboard(); }
function openWeeklyMenuModalForDate(date){ MENU_DASHBOARD_SELECTED_DATE=menuText(date)||menuTodayIso(); MENU_DASHBOARD_MONTH=menuMonthKeyFromDate(MENU_DASHBOARD_SELECTED_DATE); MENU_DASHBOARD_VIEW='menu'; return openWeeklyMenuModal(); }
function openWeeklyMenuModal(event){ if(event&&typeof event.preventDefault==='function') event.preventDefault(); if(isStandaloneWeeklyMenuPage()){ if(!MENU_DASHBOARD_SELECTED_DATE) MENU_DASHBOARD_SELECTED_DATE=menuTodayIso(); if(!MENU_DASHBOARD_MONTH) MENU_DASHBOARD_MONTH=menuMonthKeyFromDate(MENU_DASHBOARD_SELECTED_DATE); loadMenuDashboard(); return false; } ensureWeeklyMenuModal(); const modal=getMenuEl('weekly-menu-modal'); if(!modal) return false; modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); document.body.classList.add('weekly-menu-modal-open'); if(!MENU_DASHBOARD_SELECTED_DATE) MENU_DASHBOARD_SELECTED_DATE=menuTodayIso(); if(!MENU_DASHBOARD_MONTH) MENU_DASHBOARD_MONTH=menuMonthKeyFromDate(MENU_DASHBOARD_SELECTED_DATE); loadMenuDashboard(); return false; }
function closeWeeklyMenuModal(){ const modal=getMenuEl('weekly-menu-modal'); if(!modal)return; modal.classList.remove('open'); modal.setAttribute('aria-hidden','true'); document.body.classList.remove('weekly-menu-modal-open'); }
function bindWeeklyMenuTriggers(){ document.addEventListener('click', function(e){ const link=e.target.closest('a[href="weekly-menu.html"], a[href="./weekly-menu.html"], [data-weekly-menu-open="1"]'); if(!link||isStandaloneWeeklyMenuPage()) return; if(e.metaKey||e.ctrlKey||e.shiftKey||e.altKey||(link.target&&link.target==='_blank')) return; openWeeklyMenuModal(e); }); }
function loadMenuDashboard(){ const month=MENU_DASHBOARD_MONTH||menuMonthKeyFromDate(MENU_DASHBOARD_SELECTED_DATE||menuTodayIso()); const date=MENU_DASHBOARD_SELECTED_DATE||`${month}-01`; setMenuDashboardStatus('正在讀取菜單資料…', false); callGAS({type:'menuDashboard', month, date}, res=>{ if(!res||res.status!=='ok'){ MENU_DASHBOARD_CACHE=null; setMenuDashboardStatus(`菜單資料載入失敗：${menuEscape(res&&res.message?res.message:'未知錯誤')}`, true); return; } MENU_DASHBOARD_CACHE=res; MENU_DASHBOARD_MONTH=menuText(res.month||month); MENU_DASHBOARD_SELECTED_DATE=menuText(res.selected_date||date); syncMenuDashboardTitle(); renderMenuDashboardCalendar(); setMenuDashboardView(MENU_DASHBOARD_VIEW||'menu'); hideMenuDashboardStatus(); }); }
function renderMenuDashboardCalendar(){ const box=getMenuEl('menu-dashboard-calendar'), payload=MENU_DASHBOARD_CACHE; if(!box||!payload) return; const days=Array.isArray(payload.calendar_days)?payload.calendar_days:[]; if(!days.length){ box.innerHTML=''; return; } const firstDate=days[0]&&days[0].date?new Date(`${days[0].date}T00:00:00`):new Date(); const blanks=Array.from({length:firstDate.getDay()},()=>'<span class="menu-calendar-grid__blank"></span>').join(''); const todayIso=menuTodayIso(); box.innerHTML=blanks + days.map(day=>`<button type="button" class="menu-calendar-cell${menuText(day.date)===menuText(MENU_DASHBOARD_SELECTED_DATE)?' is-active':''}${menuText(day.date)===todayIso?' is-today':''}" onclick="selectMenuDashboardDate('${menuEscape(day.date)}')"><span class="menu-calendar-cell__day">${menuEscape(day.day)}</span><span class="menu-calendar-cell__dot${day.has_menu?' has-menu':''}"></span></button>`).join(''); }
function dashboardDishDefs(){ return [{key:'main',label:'主菜'},{key:'side',label:'配菜'},{key:'light_veg',label:'淺色菜'},{key:'dark_veg',label:'深色菜'},{key:'root_veg',label:'根莖瓜果'}]; }
function dashboardMealDefs(){ return [{key:'lunch',label:'午餐',tone:'lunch'},{key:'dinner',label:'晚餐',tone:'dinner'}]; }
function renderMenuMealCard(day, mealInfo){ const meal=day&&day.meals?day.meals[mealInfo.key]:null; const rows=dashboardDishDefs().map((dish,idx)=>{ const value=menuText(meal&&meal[dish.key]?meal[dish.key]:''); return `<div class="menu-meal-row"><div class="menu-meal-row__index">${idx+1}</div><div class="menu-meal-row__name${value?'':' is-empty'}">${menuEscape(value||'—')}</div><div class="menu-meal-row__tag">${menuEscape(dish.label)}</div></div>`; }).join(''); return `<section class="menu-meal-card menu-meal-card--${menuEscape(mealInfo.tone)}"><div class="menu-meal-card__head">${menuEscape(mealInfo.label)}</div><div class="menu-meal-card__body">${rows}</div></section>`; }
function renderAnalysisMetric(label,value,unit,progress,target){ const pct=Math.max(0,Math.min(100,Math.round(Number(progress||0)*100))); return `<div class="menu-analysis-metric"><div class="menu-analysis-metric__label">${menuEscape(label)}</div><div class="menu-analysis-metric__value">${menuEscape(value)}<small>${menuEscape(unit)}</small></div><div class="menu-analysis-metric__target">建議值 ${menuEscape(target)} ${menuEscape(unit)}</div><div class="menu-analysis-metric__bar"><span style="width:${pct}%"></span></div></div>`; }
function renderMenuTab(day){ if(!day||!day.has_menu) return `<section class="menu-panel-empty"><h3>這一天尚未建立菜單</h3><p>請先在 Google Sheet 菜單分頁建立當日午餐與晚餐內容。</p></section>`; const nutrition=day.nutrition_summary||{}, progress=nutrition.progress||{}; return `<section class="menu-dashboard-section"><div class="menu-meal-board">${dashboardMealDefs().map(meal=>renderMenuMealCard(day,meal)).join('')}</div><section class="menu-analysis-panel"><div class="menu-analysis-panel__title">國健署飲食對標分析（每人平均）</div><div class="menu-analysis-grid">${renderAnalysisMetric('熱量估計',menuFormatAmount(nutrition.calories,0),'kcal',progress.calories,nutrition.targets?nutrition.targets.calories:1800)}${renderAnalysisMetric('蛋白質',menuFormatAmount(nutrition.protein,1),'g',progress.protein,nutrition.targets?nutrition.targets.protein:65)}${renderAnalysisMetric('蔬菜總量',menuFormatAmount(nutrition.vegetables,0),'g',progress.vegetables,nutrition.targets?nutrition.targets.vegetables:300)}${renderAnalysisMetric('全穀雜糧',menuFormatAmount(nutrition.grains,0),'g',progress.grains,nutrition.targets?nutrition.targets.grains:220)}</div><div class="menu-analysis-panel__note">${menuEscape(nutrition.formula_note||'依菜單與 BOM 結構估算每人平均對標值。')}</div></section></section>`; }
function setMenuDashboardServings(value){ MENU_DASHBOARD_SERVINGS=menuQty(value||1); renderMenuDashboardView(); }
function renderProcurementRow(item){ const servings=menuQty(MENU_DASHBOARD_SERVINGS||1); const net=menuNum(item.per_person_net,0)*servings, loss=menuNum(item.per_person_loss,0)*servings, gross=menuNum(item.per_person_gross,0)*servings; const netFmt=menuFormatWeight(net,item.qty_unit||item.unit||'g'), lossFmt=menuFormatWeight(loss,item.qty_unit||item.unit||'g'), grossFmt=menuFormatWeight(gross,item.qty_unit||item.unit||'g'); return `<div class="menu-proc-row"><div class="menu-proc-row__item"><div class="menu-proc-row__icon">◫</div><div><div class="menu-proc-row__name">${menuEscape(item.product_name||'未命名食材')}</div><div class="menu-proc-row__meta">${menuEscape(item.category||'')}${item.spec?`｜${menuEscape(item.spec)}`:''}${item.has_linked_product?'':'｜未連商品主檔'}</div><div class="menu-proc-row__sources">${(item.source_dishes||[]).map(v=>`<span>${menuEscape(v)}</span>`).join('')}</div></div></div><div class="menu-proc-row__metric"><strong>${menuEscape(netFmt.value)}</strong><small>${menuEscape(netFmt.unit)}</small>${netFmt.sub?`<em>${menuEscape(netFmt.sub)}</em>`:''}</div><div class="menu-proc-row__metric menu-proc-row__metric--warn"><strong>${menuEscape(lossFmt.value)}</strong><small>${menuEscape(lossFmt.unit)}</small>${lossFmt.sub?`<em>${menuEscape(lossFmt.sub)}</em>`:''}</div><div class="menu-proc-row__metric menu-proc-row__metric--accent"><strong>${menuEscape(grossFmt.value)}</strong><small>${menuEscape(grossFmt.unit)}</small>${grossFmt.sub?`<em>${menuEscape(grossFmt.sub)}</em>`:''}</div></div>`; }
function menuIngredientInputId(date,groupIndex,itemIndex,productId){ return `menu-qty-${menuText(date).replace(/[^0-9]/g,'')}-${groupIndex}-${itemIndex}-${menuText(productId).replace(/[^\\w\\-]/g,'')}`; }
function renderIngredientGroup(day,group,groupIndex){ const items=Array.isArray(group&&group.items)?group.items:[]; return `<section class="menu-quickbuy-group"><div class="menu-quickbuy-group__head"><div class="menu-quickbuy-group__tag">${menuEscape(group.meal_label||'')}｜${menuEscape(group.dish_label||'')}</div><h4>${menuEscape(group.dish_name||'')}</h4></div><div class="menu-quickbuy-grid">${items.map((item,itemIndex)=>{ const inputId=menuIngredientInputId(day.date,groupIndex,itemIndex,item.product_id||item.id||item.sku); const itemJson=JSON.stringify({id:menuText(item.product_id||item.id||item.sku),sku:menuText(item.sku||item.product_id||item.id),name:menuText(item.product_name||item.name),price:menuNum(item.price,0)}).replace(/'/g,'&#39;'); return `<article class="menu-quickbuy-card"><div class="menu-quickbuy-card__title">${menuEscape(item.product_name||item.name||'')}</div><div class="menu-quickbuy-card__meta">${item.spec?`<span>${menuEscape(item.spec)}</span>`:''}${item.unit?`<span>單位 ${menuEscape(item.unit)}</span>`:''}<span>單價 $${menuEscape(menuFormatAmount(item.price,0))}</span></div><div class="menu-quickbuy-card__actions"><input id="${menuEscape(inputId)}" type="number" min="1" step="1" value="${menuIntQty(item.default_qty||1)}"><button type="button" onclick='addMenuIngredientToCart(${itemJson}, "${menuEscape(inputId)}")'>加入購物車</button></div></article>`; }).join('')}</div></section>`; }
function pushCartItemSilently(item,qty){ if(!item||!item.id)return false; const addQty=menuIntQty(qty); if(typeof getCart!=='function'||typeof setCart!=='function'){ if(typeof addToCart==='function'){ addToCart(item,addQty); return true; } return false; } const cart=getCart(); const exist=cart.find(i=>String(i.id)===String(item.id)); if(exist) exist.qty=menuIntQty(Number(exist.qty||0)+addQty); else cart.push({...item, qty:addQty}); setCart(cart); if(typeof updateCartCount==='function') updateCartCount(); return true; }
function addMenuIngredientToCart(item,qtyInputId){ if(!item||!item.id)return; const qtyEl=qtyInputId?document.getElementById(qtyInputId):null; const qty=qtyEl?menuIntQty(qtyEl.value):1; if(typeof addToCart==='function') addToCart(item,qty); else { pushCartItemSilently(item,qty); alert(`${item.name} 已加入購物車（${qty} 件）`); } }
function addSelectedDayIngredientsToCart(){ const day=currentMenuDay(); if(!day||!Array.isArray(day.ingredient_groups)||!day.ingredient_groups.length){ alert('這一天目前沒有可加入購物車的對應食材。'); return; } let addedRows=0; day.ingredient_groups.forEach((group,groupIndex)=>{ (group.items||[]).forEach((item,itemIndex)=>{ const inputId=menuIngredientInputId(day.date,groupIndex,itemIndex,item.product_id||item.id||item.sku); const input=document.getElementById(inputId); const raw=input?Number(input.value):Number(item.default_qty||1); if(!Number.isFinite(raw)||raw<=0)return; const qty=menuIntQty(raw); const ok=pushCartItemSilently({id:menuText(item.product_id||item.id||item.sku),sku:menuText(item.sku||item.product_id||item.id),name:menuText(item.product_name||item.name),price:menuNum(item.price,0)}, qty); if(ok) addedRows += 1; }); }); if(!addedRows){ alert('請先填入有效數量，再加入購物車。'); return; } alert(`已將 ${addedRows} 項食材加入購物車。`); }
function renderProcurementTab(day){ if(!day||!day.has_menu) return `<section class="menu-panel-empty"><h3>這一天尚未建立菜單</h3><p>請先建立當日午餐與晚餐內容，再進行採購試算。</p></section>`; const items=Array.isArray(day.procurement_items)?day.procurement_items:[], groups=Array.isArray(day.ingredient_groups)?day.ingredient_groups:[], unmapped=Array.isArray(day.procurement_unmapped_dishes)?day.procurement_unmapped_dishes:[], servings=menuQty(MENU_DASHBOARD_SERVINGS||1); const groupHtml=groups.length?`<section class="menu-quickbuy-panel"><div class="menu-quickbuy-panel__head"><div><div class="menu-section-mini">對應食材 / 快速加入購物車</div><p>這一區使用菜單管理中的「加入購物車」用途，方便將已建好的商品直接加入購物車。</p></div><button type="button" class="menu-bulk-btn" onclick="addSelectedDayIngredientsToCart()">本日食材全部加入購物車</button></div>${groups.map((group,idx)=>renderIngredientGroup(day,group,idx)).join('')}</section>`:''; return `<section class="menu-dashboard-section"><div class="menu-proc-hero"><div><div class="menu-proc-hero__title">智慧食材採購清單</div><div class="menu-proc-hero__sub">上方輸入供餐人數，下方會直接帶入當日菜單對應的原形食材與建議採購量。</div></div><label class="menu-proc-hero__count"><span>供餐人數</span><input type="number" min="1" step="1" value="${menuEscape(menuFormatAmount(servings,0))}" onchange="setMenuDashboardServings(this.value)"></label></div><div class="menu-proc-board"><div class="menu-proc-board__head"><span>食材原形（BOM 子件）</span><span>必須使用量（淨重）</span><span>預估耗損量</span><span>建議採購量（毛重）</span></div>${items.length?items.map(item=>renderProcurementRow(item)).join(''):`<div class="menu-panel-empty is-inline"><h3>尚未建立採購試算對應</h3><p>請在菜單管理勾選「採購試算」，並填寫每人用量與耗損率。</p></div>`}</div>${unmapped.length?`<div class="menu-warning-box"><div class="menu-warning-box__title">以下菜色尚未建立採購試算對應</div><div class="menu-warning-box__list">${unmapped.map(v=>`<span>${menuEscape(v.meal_label||'')}｜${menuEscape(v.dish_name||'')}</span>`).join('')}</div></div>`:''}<div class="menu-proc-footnote">${menuEscape(`採購量計算＝(每人淨量 × ${menuFormatAmount(servings,0)} 人) ÷ (1 - 耗損率)。`)}</div>${groupHtml}</section>`; }
function renderMenuDashboardView(){ const box=getMenuEl('menu-dashboard-view'); if(!box)return; const day=currentMenuDay(); if(!MENU_DASHBOARD_CACHE){ box.innerHTML=''; return; } if(MENU_DASHBOARD_VIEW==='procurement'){ box.innerHTML=renderProcurementTab(day); return; } box.innerHTML=renderMenuTab(day); }
document.addEventListener('keydown', e=>{ if(e.key==='Escape') closeWeeklyMenuModal(); });
document.addEventListener('DOMContentLoaded', ()=>{ bindWeeklyMenuTriggers(); if(typeof updateMemberArea==='function') updateMemberArea(); if(typeof updateCartCount==='function') updateCartCount(); if(isStandaloneWeeklyMenuPage()){ initStandaloneDashboard(); MENU_DASHBOARD_SELECTED_DATE=menuTodayIso(); MENU_DASHBOARD_MONTH=menuMonthKeyFromDate(MENU_DASHBOARD_SELECTED_DATE); loadMenuDashboard(); } else { ensureWeeklyMenuModal(); if(isShopIndexMenuRail()) loadShopMenuRail(); } });
